import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';

import './globals.css';
import { cn } from '@/lib/utils';
//import { authOptions } from '@/lib/auth/authoption';
//import { getServerSession } from 'next-auth';
import { QueryProvider } from '@/providers/query-providers';


const fontSans = FontSans({
    subsets: ['latin'],
    variable: '--font-sans',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    //const session = await getServerSession(authOptions);

    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={cn(
                    'min-h-screen bg-background font-sans antialiased',
                    fontSans.variable
                )}>
                <QueryProvider>{children}</QueryProvider>    
            </body>
        </html>
    );
}